network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:  
      dhcp4: true
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]  
    enp0s8: 
      addresses: [192.168.100.1/24]     
      dhcp4: no